// Code generated by github.com/norbux/gqlgen, DO NOT EDIT.

package model

type EmailHost struct {
	ID string `json:"id"`
}

func (EmailHost) IsEntity() {}

type Manufacturer struct {
	ID string `json:"id"`
}

func (Manufacturer) IsEntity() {}
